name: "Build"
on:
  pull_request:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v27
    - run: nix build
    - run: cp result mqt-qcec-diff-presentation.pdf
    - uses: actions/upload-artifact@v4
      with:
        name: mqt-qcec-diff-presentation
        path: mqt-qcec-diff-presentation.pdf
